### PR TITLE
Basic pass of known ips

### PR DESCRIPTION
**Pull request by elduddz**
if not default value is an empty array, which looks to work on other ones.

### CODE REVIEW

**Comment by MarcDenman** [comment]
@elduddz Can you confirm that adding that adding the default of an empty array doesn't nuke whatever default Azure adds in?

**Comment by elduddz** [comment]
@MarcDenman when I looked at some of the setups they already had a dns element that was set with = []

https://ukhogov.visualstudio.com/Digital%20Operations/_build/results?buildId=31920&view=logs&j=a0577d27-9a57-50c8-afe0-d78816a440aa&t=ae15bfc6-9a9c-5013-5af0-c9a2af485ff1&l=164

**Comment by elduddz** [comment]
just needed to double check I am not sure that azure defaults anything, from a lot of the setup it looks like it is an empty array.

if we want to domain join something we would probably need to set this, and the spokes is currently wiping out all the values now anyway?

**Comment by MarcDenman** [comment]
> just needed to double check I am not sure that azure defaults anything, from a lot of the setup it looks like it is an empty array.
> 
> if we want to domain join something we would probably need to set this, and the spokes is currently wiping out all the values now anyway?

I took a look yesterday in Azure at the diff before and after of when this is accidentally removing the DNS values, they def get replaced with an `[]` so this is good to go.

**Pull request merged**
